### ISSUE TITLE
How to make HR and LR be paired?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [epishchik/SRGD#2]
Amazing work! 
I found there are HR and LR images not pixel-wise aligned (there are pixel shifts or special effects in the HRs). Are they captured from different timestamps? How to make sure that HR and LR images are paired?

**Comment by epishchik** [comment]
Hey, thanks!

There is no real way to align some images, because I couldn't align them perfectly in UE when I was rendering scenes, sometimes UE just shifts rendering and as I've found you can't do much with it :(

I think it's better to just drop such pairs.

**Comment by yuqing-liu-dut** [comment]
Thank you for your reply. I'll manually drop the pairs.
